// Declaring Variables
let numberVariable = 5;
let stringVariable = "Hello, World!";
let booleanVariable = true;

// Operators
let sum = 5 + 3;
let difference = 10 - 4;
let product = 6 * 2;
let quotient = 8 / 2;

// String Concatenation
let firstName = "xyz";
let lastName = "drd";
let fullName = firstName + " " + lastName;

// Comparison 
let isEqual = 5 === 5;
let isNotEqual = 5 !== 7;
let isGreaterThan = 10 > 5;
let isLessThan = 3 < 8;

// Logical Operators
let andOperator = true && false;
let orOperator = true || false;
let notOperator = !true;

// Displaying Output
console.log("Number Variable:", numberVariable);
console.log("String Variable:", stringVariable);
console.log("Boolean Variable:", booleanVariable);

console.log("Sum:", sum);
console.log("Difference:", difference);
console.log("Product:", product);
console.log("Quotient:", quotient);

console.log("Full Name:", fullName);

console.log("Is Equal:", isEqual);
console.log("Is Not Equal:", isNotEqual);
console.log("Is Greater Than:", isGreaterThan);
console.log("Is Less Than:", isLessThan);

console.log("AND Operator:", andOperator);
console.log("OR Operator:", orOperator);
console.log("NOT Operator:", notOperator);